### ISSUE TITLE
[REFACTOR] 유저 서비스 로직 수정 및 리팩토링

### ISSUE THREAD

**Issue by jsjune** [DB-Dive/insta_clone#20]
## 📝 todo
- [x] 회원가입 및 로그인 validation 추가
- [x] 토큰 예외처리 추가
- [x] follow, unfollow 로직 수정
- [x] following 조회 api 수정
